import os
import random
from generate_fasta_v1 import generate_mult_fasta

# 83_S1 Serine at codon 83 reference gyrae for ecoli
AGC_83 = ("ATGAGCGATCTGGCGCGCGAAATTACCCCGGTGAACATTGAAGAAGAACTGAAAAGCAGCTATCTGGATT"
        "ATGCGATGAGCGTGATTGTGGGCCGCGCGCTGCCGGATGTGCGCGATGGCCTGAAACCGGTGCATCGCCG"
        "CGTGCTGTATGCGATGAACGTGCTGGGCAACGATTGGAACAAAGCGTATAAAAAAAGCGCGCGCGTGGTG"
        "GGCGATGTGATTGGCAAATATCATCCGCATGGCGATAGCGCGGTGTATGATACCATTGTGCGCATGGCGC"
        "AGCCGTTTAGCCTGCGCTATATGCTGGTGGATGGCCAGGGCAACTTTGGCAGCATTGATGGCGATAGCGC"
        "GGCGGCGATGCGCTATACCGAAATTCGCCTGGCGAAAATTGCGCATGAACTGATGGCGGATCTGGAAAAA"
        "GAAACCGTGGATTTTGTGGATAACTATGATGGCACCGAAAAAATTCCGGATGTGATGCCGACCAAAATTC"
        "CGAACCTGCTGGTGAACGGCAGCAGCGGCATTGCGGTGGGCATGGCGACCAACATTCCGCCGCATAACCT"
        "GACCGAAGTGATTAACGGCTGCCTGGCGTATATTGATGATGAAGATATTAGCATTGAAGGCCTGATGGAA"
        "CATATTCCGGGCCCGGATTTTCCGACCGCGGCGATTATTAACGGCCGCCGCGGCATTGAAGAAGCGTATC"
        "GCACCGGCCGCGGCAAAGTGTATATTCGCGCGCGCGCGGAAGTGGAAGTGGATGCGAAAACCGGCCGCGA"
        "AACCATTATTGTGCATGAAATTCCGTATCAGGTGAACAAAGCGCGCCTGATTGAAAAAATTGCGGAACTG"
        "GTGAAAGAAAAACGCGTGGAAGGCATTAGCGCGCTGCGCGATGAAAGCGATAAAGATGGCATGCGCATTG"
        "TGATTGAAGTGAAACGCGATGCGGTGGGCGAAGTGGTGCTGAACAACCTGTATAGCCAGACCCAGCTGCA"
        "GGTGAGCTTTGGCATTAACATGGTGGCGCTGCATCATGGCCAGCCGAAAATTATGAACCTGAAAGATATT"
        "ATTGCGGCGTTTGTGCGCCATCGCCGCGAAGTGGTGACCCGCCGCACCATTTTTGAACTGCGCAAAGCGC"
        "GCGATCGCGCGCATATTCTGGAAGCGCTGGCGGTGGCGCTGGCGAACATTGATCCGATTATTGAACTGAT"
        "TCGCCATGCGCCGACCCCGGCGGAAGCGAAAACCGCGCTGGTGGCGAACCCGTGGCAGCTGGGCAACGTG"
        "GCGGCGATGCTGGAACGCGCGGGCGATGATGCGGCGCGCCCGGAATGGCTGGAACCGGAATTTGGCGTGC"
        "GCGATGGCCTGTATTATCTGACCGAACAGCAGGCGCAGGCGATTCTGGATCTGCGCCTGCAGAAACTGAC"
        "CGGCCTGGAACATGAAAAACTGCTGGATGAATATAAAGAACTGCTGGATCAGATTGCGGAACTGCTGCGC"
        "ATTCTGGGCAGCGCGGATCGCCTGATGGAAGTGATTCGCGAAGAACTGGAACTGGTGCGCGAACAGTTTG"
        "GCGATAAACGCCGCACCGAAATTACCGCGAACAGCGCGGATATTAACCTGGAAGATCTGATTACCCAGGA"
        "AGATGTGGTGGTGACCCTGAGCCATCAGGGCTATGTGAAATATCAGCCGCTGAGCGAATATGAAGCGCAG"
        "CGCCGCGGCGGCAAAGGCAAAAGCGCGGCGCGCATTAAAGAAGAAGATTTTATTGATCGCCTGCTGGTGG"
        "CGAACACCCATGATCATATTCTGTGCTTTAGCAGCCGCGGCCGCGTGTATAGCATGAAAGTGTATCAGCT"
        "GCCGGAAGCGACCCGCGGCGCGCGCGGCCGCCCGATTGTGAACCTGCTGCCGCTGGAACAGGATGAACGC"
        "ATTACCGCGATTCTGCCGGTGACCGAATTTGAAGAAGGCGTGAAAGTGTTTATGGCGACCGCGAACGGCA"
        "CCGTGAAAAAAACCGTGCTGACCGAATTTAACCGCCTGCGCACCGCGGGCAAAGTGGCGATTAAACTGGT"
        "GGATGGCGATGAACTGATTGGCGTGGATCTGACCAGCGGCGAAGATGAAGTGATGCTGTTTAGCGCGGAA"
        "GGCAAAGTGGTGCGCTTTAAAGAAAGCAGCGTGCGCGCGATGGGCTGCAACACCACCGGCGTGCGCGGCA"
        "TTCGCCTGGGCGAAGGCGATAAAGTGGTGAGCCTGATTGTGCCGCGCGGCGATGGCGCGATTCTGACCGC"
        "GACCCAGAACGGCTATGGCAAACGCACCGCGGTGGCGGAATATCCGACCAAAAGCCGCGCGACCAAAGGC"
        "GTGATTAGCATTAAAGTGACCGAACGCAACGGCCTGGTGGTGGGCGCGGTGCAGGTGGATGATTGCGATC"
        "AGATTATGATGATTACCGATGCGGGCACCCTGGTGCGCACCCGCGTGAGCGAAATTAGCATTGTGGGCCG"
        "CAACACCCAGGGCGTGATTCTGATTCGCACCGCGGAAGATGAAAACGTGGTGGGCCTGCAGCGCGTGGCG"
        "GAACCGGTGGATGAAGAAGATCTGGATACCATTGATGGCAGCGCGGCGGAAGGCGATGATGAAATTGCGC"
        "CGGAAGTGGATGTGGATGATGAACCGGAAGAAGAA")
# double ref
double_ref = AGC_83 + AGC_83

# double mut
mut = AGC_83[:246] + 'TTT' + AGC_83[249:]
double_mut = mut + mut

# random double
def generate_random_dna(length=2625):
    return ''.join(random.choices('ACTG', k=length))
random = generate_random_dna()
double_random = random + random

# making fasta objects for generate_mult_fasta
seqs = [
    (double_ref, "double_83_ref"),
    (double_mut, "double_83_TTT"),
    (double_random, "double_random"),
]

generate_mult_fasta(seqs, "input/double_genes.fasta")

